### ISSUE TITLE
Scrape data from Buoy 44065

### ISSUE THREAD

**Issue by kylejb** [Grieze/Surf-Reporter#1]
Scrape relevant weather data from buoy that is closest to our beach break.

## How

- Decide on language/framework (e.g., Python, JavaScript). Regardless of language, the process is fundamentally similar to what you did for your Reuters repo.

- See resources

## Why

The API that you will create later will need this logic. 

---

### Resources

- [NDBC Documentation](https://www.ndbc.noaa.gov/docs/ndbc_web_data_guide.pdf)

- [Buoy #44065](https://www.ndbc.noaa.gov/station_page.php?station=44065)

**Comment by Grieze** [comment]
Just finished, it's a tad bit slow, but it gets the job done, that's also because it has run time of O(3n). Lmk if this is good to move on with.

**Comment by kylejb** [comment]
> Just finished, it's a tad bit slow, but it gets the job done, that's also because it has run time of O(3n). Lmk if this is good to move on with.

@Grieze:

For future submissions, create a [PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). It's how you'd normal work once you're on a team; it makes it easy for others to review code before it gets committed to your primary branch.

Some feedback:

- Loving the organization and formatting; your code is easy to read; it's a skill that I have yet to master, so it's awesome to see you focusing on that already!
- I recommend [developing a consistent pattern in how you write git commit messages](https://www.conventionalcommits.org/en/v1.0.0/); if you don't find it useful, others reading your code will definitely appreciate the thoughtfulness.
- Writing to a file [as you did here](https://github.com/Grieze/Surf-Reporter/blob/main/webscraper/dataScraperAPI.js#L67-L73) is the right intention; I think it's a great idea to save this data for future use. However, explicitly writing data to a file is not necessary or prudent in this context. This logic you built will live in the backend as a service; it will send (e.g., HTTP protocol) the required data to the frontend (i.e., web app) upon request.
- Generally speaking, relying on CSS selector patterns like [you did here](https://github.com/Grieze/Surf-Reporter/blob/main/webscraper/dataScraperAPI.js#L17) for web scraping is brittle. In light of the data structure, I think you made a great choice to focus on the data structure of the table rather than other elements. However, if you take a peek at some of the documentation I provided in this issue, you will discover alternate methods to get the data without scraping by HTML. You can use one of their XML files that have more defined structure or one of their endpoints as well.

### Next steps

- Start creating Pull Requests instead of pushing your code directly onto your primary branch. It's a bad habit. Let me know if you're not comfortable with `git` commands, and I'll give you more guidance.
- Once you get up to [this part](https://github.com/Grieze/Surf-Reporter/issues/2), I recommend you try to refactor your scraper before integrating it. The functional objective is to improve its performance; not nice to keep people waiting for surf reports. 😁
- Keep up the great work!
